### ISSUE TITLE
Mapping HealthcareProvider::DepartmentSpecialty

### ISSUE THREAD

**Issue by jduwel** [Nictiz/Nictiz-R4-zib2020#100]
[30-Jun 16:05] Jorn Duwel
Is het wel logisch dat AfdelingSpecialisme op de HealthcareProvider Organization.type staat en niet op de Location.type?

​[30-Jun 16:10] Jorn Duwel
    Hoe ik er op kom: als je de Example op zibs.nl omzet naar FHIR, maakt hij zowel een Location en een Organization. Maar die Location is echt een holle resource, er staat echt niks van waarde in. Dus toen zat ik eens te kijken wat nou 'onderscheidend' was en je hebt uiteraard OrganisatieLocatie, maar die zit niet in het voorbeeld (🤦‍♂️), maar toen viel AfdelingSpecialisme me op.

​[30-Jun 16:11] Jorn Duwel
    Is een AfdelingSpecialisme iets van een Locatie? Nou nee niet per se, maar óók niet van een Organisatie lijkt me. Dus de vraag is waar past hij het best denk ik

**Comment by ArdonToonstra** [comment]
Agreed that DepartmentSpecialty does not map neatly on `Organization.type` as well as `Location.type`. 

One, maybe important, difference is that `Location.type` has an extensible binding to [ServiceDeliveryLocationRoleType](http://hl7.org/fhir/v3/ServiceDeliveryLocationRoleType/vs.html) while `Organization.type` has an example binding. Therefore, our COD016-VEKT codes are easier mapped to `Organization.type`. No need for a very big ConceptMap to map codes.

So I think I am in favor of keeping the mapping of DepartmentSpecialty on Organization.type.

**Comment by jduwel** [comment]
I actually think that COD016-VEKT (https://www.vektis.nl/standaardisatie/codelijsten/COD016-VEKT#inhoud) has lots of overlap with http://hl7.org/fhir/v3/ServiceDeliveryLocationRoleType/vs.html

So I would actually consider that an argument FOR mapping DepartmentSpecialty on Location.type. 
Is that easy? No not at all, but is 'easiest' a good reason?

However, COD016-VEKT is actually a 'zorgverleners'-codelist and not a 'zorgaanbieders'-codelist, it talks about _persons_, not either organizations or locations. So maybe that would be a zib-ticket?

**Comment by pieter-edelman-nictiz** [comment]
I think it's hard to say something in general about this. Organization is a hierarchical concept; it's perfectly possible that a large organization has a specialized branch with multiple locations. In this case you would get an Organization with a specialty with multiple Location resources. In other cases, it is the location that represents a specialty of an Organization. And in other situations, an organization has multiple locations but a specialty is found at some of them.

The zib just doesn't care; every physical location is a zib HealhtcareProvider instance. In our mapping, we split it over two resources. From this viewpoint, both the Location and the Organization are guaranteed to offer the specialty, but it's not guaranteed that either the Location or the Organization offers the specialty. However, I think it makes sense that a zib instance will be as close to the specialism as possible, thus that the zib represents one location of an organization or division that offers the specialty. In this case Organization will be the correct place and not Location (because there might be other locations). In other words: when the zib represents a location that is the only place that offers that specialty, the rest of the elements will probably represent that specialty as well. For this reason, I think Organization is the best (or least bad) mapping and not Location.

**Comment by ArdonToonstra** [comment]
@jduwel ,
>However, COD016-VEKT is actually a 'zorgverleners'-codelist and not a 'zorgaanbieders'-codelist, it talks about persons, not either organizations or locations. So maybe that would be a zib-ticket?

That feels worthy of a zib ticket/question to see if there is a more appropriate list of DepartmentSpecialty. Although I believe the Vektiz list contains some relevant codes. Also supported by this ticket: https://bits.nictiz.nl/browse/ZIB-464 that states: "De Vektislijst is een combinatie van specialismen, typen zorgverleners, maar ook instellingen als verpleeghuizen staan erin."

Moreover, I can follow the reasoning of Pieter.

**Comment by jduwel** [comment]
Re: the ValueSet, thanks for the ticket. So that has probably already been discussed.

I think `Location.type` is the least bad mapping. From a zib perspective I can follow Pieter's logic, so in a 'zib-only' world, we could get away with `Organization.type`. However, isn't it the point of FHIR to allow for a more broad data exchange? The granularity of DepartmentSpecialty matches `Location.type` better then `Organization.type`, so in a more broader context I would expect the data to be there.

**Comment by ArdonToonstra** [comment]
Likely, I will now be swearing in the church: what of mapping them to both elements?

**Comment by ArdonToonstra** [comment]
Meeting conclusion. least bad option: only map in `Organization.type`. Location only goes about the physical location. Also noteworthy comment in the Location spec: _"Note: Wards/departments are not part of this structure - these would form part of the Organizational Hierarchy."_ The Vektiz valueset is too broad to purely map on `Location.type`.

For now, we will close this issue and live with the status quo.
