### ISSUE TITLE
Mapping of 'RelatieZorgepisode' in MedicationAgreement and DispenseRequest

### ISSUE THREAD

**Issue by ArdonToonstra** [Nictiz/Nictiz-R4-zib2020#105]
The MP9 dataset has the concept RelatieZorgepisode that links the MedicationRequest to an EpisodeOfCare. With R4, the reference to EpisodeOfCare has been removed. Only a reference to Encounter can be made natively which in turn can reference the EpisodeOfCare. 

In the comment on `MedicationRequest.encounter` is written: 'If there is a need to link to episodes of care they will be handled with an extension.'. However, the only available extension that looks usable is not allowed to be used in MedicationRequest in R4: https://hl7.org/FHIR/r4/extension-workflow-episodeofcare.html.

In the build version this is solved: http://build.fhir.org/extension-workflow-episodeofcare.html.

For now I propose to place an implicit mapping on `MedicationRequest.encounter` that states that the mapping of RelatieZorgepisode is placed on `Encounter.episodeOfCare`. Would this work? Or do we need to create a custom extension.

**Comment by weteringac** [comment]
Please also look at what has been done / will be done for information standards general practitioner / ketenzorg. The requirement for these relations have their source in the world of general pratitioners (and are very ubiquitous in that environment). It would be nice to have a consistent solution.

**Comment by ArdonToonstra** [comment]
@ahenket , can you think along for how the information standard GP data will want to tackle this problem? Any helpful thoughts?

**Comment by ArdonToonstra** [comment]
@pieter-edelman-nictiz , do you have an opinion about this?

**Comment by pieter-edelman-nictiz** [comment]
The FHIR native version cannot be used on MedicationRequest in R4, but the build version that you linked allows for this context. We could mock this FHIR extension in order to pre-adopt this wider range, but then you would need to restrict/add the target profile to the nl-core version in the using profiles, while you'd still not use an actual core extension. So in this case it would maybe be better to just use a custom extension.

The current version of said extension can be found here: https://simplifier.net/nictizstu3-zib2017/extension-context-nl-core-episodeofcare and is a generic mechanism to link an nl-core-episodeofcare instance.

**Comment by ArdonToonstra** [comment]
I will mimic the STU3 custom extension for R4 and make a comment/note that from R4 onwards, the extension will likely be replaced by a HL7 core extension.

I also edited my initial issue description to make it more clear that the extension is not usable in R4, but the build version shows this will be fixed in R5.

**Comment by ArdonToonstra** [comment]
This has been added to the profiles, therefore I will close the ticket. It can be reopened if the approach needs to be fundamentally different. Normal feedback will follow during the review procedures.
