### ISSUE TITLE
How to map the concept DesiredHealthCondition::FunctionalOrMentalStatus from the zib TreatmentObjective? 

### ISSUE THREAD

**Issue by Ashwin-nictiz** [Nictiz/Nictiz-R4-zib2020#111]
The element **DesiredHealthCondition::FunctionalOrMentalStatus** was mapped in STU3 to Goal.target.measure and Goal.target.detail[x]. It also contains a reference to the zib-FunctionalOrMentalStatus.

The comment to the elements describes as follows:

_The HCIM TreatmentObject states a reference to the observations GeneralMeasurement or FunctionalOrMentalStatus to provide information on the Goal's target. This profile uses the Goal elements target.measure and target.detail to record this information inside the Goal resource. The Observation.code maps to target.measure and Observation.value maps to target.detail.
The gol-1 constraints requires that both elements are given if target.measure or target.detail is used._

In the ZIB I only see 1 reference and that is FunctionalOrMentalStatus and no reference to GeneralMeasurement.

A potential solution:

Is it possible to place the two elements in 1 extension instead of mapping on Goal.target.measure and Goal.target.detail[x]?

Example: Goal.target.extension:desiredHealthCondition.valueReference with a reference to FunctionalOrMentalStatus

**Comment by pieter-edelman-nictiz** [comment]
The GeneralMeasurement reference stems from the 2017 version of the zib. This reference is removed in the 2020 version so we don't have to deal with this anymore.

About this reference: the FuctionalOrMentalStatus is profiled om an Observation, ie. it represents something that has been observed in the past. Zib TreatmentObjective describes a desired result, i.e. something in the future. Using an actual reference to the Observation instance would therefore semantically be incorrect, and I suspect this is the reason that it is not used in the STU3 version (although it hasn't been described very well).

However, the Goal resource offers the necessary parts to represent a FunctionalOrMentalStatus in the future. Therefore it seems like a better approach to model FunctionalOrMentalStatus directly as part of this profile.

Note that this is a recurring weakness between the zibs and FHIR: the zibs are not time bound; they can be instantiated at will as something that will happen in the future. Whereas FHIR is more down to earth, and things have to be an explicit measurement or intention.

**Comment by ahenket** [comment]
After back&forth we came to the following mapping. This maps the properties of FunctionalOrMentalStatus into Goal as per the idea vented in this issue. It purposefully does not map FunctionalOrMentalStatus.StatusDate as this is defined as "Date on which the status was determined. A ‘vague’ date, such as only the year, is permitted.". Since we are in the context of a Goal you might map StatusDate onto the Goal.target.dueDate, but that seems to be inconsistent with its definition.

One wonders why the CIM TreatmentObjective does not have a target/due date as property.

HCIM TreatmentObjective-v3.1(2017EN) | HCIM TreatmentObjective | Comments
-- | -- | --
NL-CM:13.5.1 | Goal | TreatmentObjective
NL-CM:13.5.5 | Goal.description | DesiredHealthcareResult
NL-CM:4.26.2 | Goal.target.measure | FunctionalOrMentalStatus.StatusName
NL-CM:4.26.3 | Goal.target.detailCodeableConcept | FunctionalOrMentalStatus.StatusValue
NL-CM:4.26.5 | Goal.target.detailCodeableConcept.extension | FunctionalOrMentalStatus.MedicalDevice
NL-CM:4.26.4 | Goal.note | FunctionalOrMentalStatus.Comment
NL-CM:13.5.4 | Goal.addresses | Problem

**Comment by ArdonToonstra** [comment]
I think we can close this issue as we have chosen the approach described in this ticket: FunctionalOrMentalStatus is profiled inside the Goal resource instead of a reference.
