### ISSUE TITLE
Add guidance on SearchParameters in Profiling Guidelines and update tooling

### ISSUE THREAD

**Issue by ArdonToonstra** [Nictiz/Nictiz-R4-zib2020#139]
Currently, no guidance exists for SearchParameters in the Profiling Guidelines. I believe you would add SearchParameters only from the nl-core layer onwards. The zib layer is without use case definitions.

 **Preliminary** proposal to add sections:

11.1.1.6 SearchParameters
The `id` will be constructed as: English translation of the functional concept used to search, only lowercase ASCII characters. Words separated by a dash ('-').
The canonical `URL` will then be: http://nictiz.nl/fhir/SearchParameter/[id]
The `name` will be [id] capitalized and with dashes and such removed, unless a better scheme is deemed more appropriate.
The `code`: [id]
The `description` will describe the working of the search parameter.
The `purpose` will be populated to indicate why the SearchParameter is created.

The `expression` is provider rather than `xpath`. 

11.1.2 Folder structure and file name
resources/searchparameter-[id].xml

**Comment by ArdonToonstra** [comment]
Added proposal in wiki: https://informatiestandaarden.nictiz.nl/wiki/FHIR:Vissue-github-139_FHIR_Profiling_Guidelines_R4#Practical_guidelines 
To do: 
- review wiki
- created StructureDefinition for SearchParameter for QA tooling
- incorporated this in QA

**Comment by jduwel** [comment]
> The id will be constructed as: English translation of the functional concept used to search, only lowercase ASCII characters. Words separated by a dash ('-').

This has been applied as 'searchparameter-category' as an id. I would not say that is completely covering the functional concept as you have no idea _what_ category. 'category' is the SearchParameter.code and the FHIR element that is being searched on (see comment below).

Involving resourceType here (like 'searchparameter-[resource type]-[code] would not be pretty, because this param is created for two resourceTypes, and 'searchparameter-MedicationDispense-MedicationAdministration-category' I think we should avoid.

STU3 does this as 'searchparameter-Medication-category', but how can we extend this to other parameters we would like to define? If resourcetype.count() gt 1, then resource group? (It should be 'Medications' then)

> The code: [id]

I would say the code does not have to be the [id]. I would say that if the parameter searches on a specific FHIR element, the name of this element should be the code. _Else_ the id (or the functional concept).

Also: FHIR guidelines state the code should contain hyphens if multiple words, maybe good to explicitly state this.

**Comment by pieter-edelman-nictiz** [comment]
Adjusted proposal: https://informatiestandaarden.nictiz.nl/wiki/FHIR:Vissue-github-139_FHIR_Profiling_Guidelines_R4#SearchParameters

**Comment by pieter-edelman-nictiz** [comment]
Pull request for QA: https://github.com/Nictiz/Nictiz-R4-zib2020/pull/255

**Comment by pieter-edelman-nictiz** [comment]
Merged the text. I'm closing this issue
