### ISSUE TITLE
Implement already approved but not yet implemented changes in zibs?

### ISSUE THREAD

**Issue by LuudSlagter** [Nictiz/Nictiz-R4-zib2020#168]
Suppose a zib has some related zib tickets wherein changes have been proposed (for example textual changes), which are already approved, but have not been implemented/released yet in the zib itself. Do we already implement these changes in our own code, or do we have to wait until the changes in question have been implemented in the zib itself?

Perhaps we need to distinguish between several types of changes; for instance textual changes in descriptions/concepts such as typos (e.g. https://bits.nictiz.nl/browse/ZIB-1578) could be corrected as soon as possible in our own code (so as to avoid possible confusion for implementers), while more drastic changes in the structure of the zib could be postponed until these are actually released.

**Comment by ArdonToonstra** [comment]
- Still discussion about whether or not to solve zib fixes/known typos 
- Consensus to fix more fundamental problems that are acknowledged by the zib.
  - How to consistently document known deviations from the zib ( known-issues.yml, comment in profile or other means)
- Luud will enquire with Marc about how they solve this in the HL7v3 CDA domain.

**Comment by pieter-edelman-nictiz** [comment]
My viewpoint is that the FHIR level is _not_ te place to fix issues that exists on the functional level. In other words: as long as the issue exists in the zib (or any other functional model), it will not be fixed on the FHIR level.

There are multiple reasons for this viewpoint. On a fundamental level, I think it's dangerous that the functional and FHIR level deviate from each other (even if documented properly). On a practical level, this might become messy very quickly; what should the information standards regard as the truth when using a zib? How should you handle this in ART-DECOR? What should users of the profiles consider the truth?

Practically, this viewpoint would lead to the following guidelines:
* If an error is trivial _and_ recognized by the zib centrum, than we can adopt it (spelling mistakes).
* If an error is not trivial:
  * If the zib centrum fixes it with an erratum, then we'll adopt it.
  * Otherwise, we don't adopt it.
    * If this means that a profile can still be made, then we'll publish a profile with an error.
    * If this means a profile cannot be made, than we don't publish a profile.

**Comment by LuudSlagter** [comment]
Related to #234 and #271.

**Comment by pieter-edelman-nictiz** [comment]
This guidance should be written down in the profiling guidelines.

**Comment by pieter-edelman-nictiz** [comment]
Written down in https://informatiestandaarden.nictiz.nl/wiki/FHIR:Vissue-168_FHIR_Profiling_Guidelines_R4#Handling_errors.2C_proposed_changes_and_omissions_in_the_functional_model

**Comment by LuudSlagter** [comment]
Should 'If the conformance resources can be made, the error is documented with a hyperlink to the BITS ticket.' be changed to 'If the conformance resources can be made, the error is documented in the resources themselves with a hyperlink to the BITS ticket.'?

**Comment by LuudSlagter** [comment]
No other comments from my side!

**Comment by pieter-edelman-nictiz** [comment]
I figured this was implicit, as it was already stated in the general guidelines. I've repeated the line from the general guidelines here.

**Comment by pieter-edelman-nictiz** [comment]
This text has been published in the meantime, marking this issue as resolved.
