### ISSUE TITLE
Consider zib-PulseRate as a vital signs profile?

### ISSUE THREAD

**Issue by Ashwin-nictiz** [Nictiz/Nictiz-R4-zib2020#228]
In STU3 we considered the zib-PulseRate as a Vital Signs profile. The HeartRate and PulseRate are similar, but they differ in content. HL7 itself makes no distinction and there is no profile available for PulseRate.

There are a number of options:

1. We consider PulseRate as a vital signs profile and with this we deviate from the HL7 vital signs.

2. PulseRate becomes 'just' a profile based on resource observation.

**Comment by pieter-edelman-nictiz** [comment]
My 2c: the intent of the Vital Signs specification in FHIR core is to model all vital signs Observations in a similar manner in order to gain maximum interoperability. This includes the listed vital sign observations for which FHIR core profiles exist, but also other vital sign observations -- it would be weird to consider it _not_ to be a Vital Signs Observation just because there's no specific equivalent profile from FHIR core. Therefore I think it makes sense to model zib PulseRate on the Vital Signs pattern we created (if the HL7 Vital Signs profile would be suitable to model the zibs on, it would probably be a no-brainer to use it for zib PulseRate).
