### ISSUE TITLE
Textual changes in PharmaceuticalProduct (originating from MP) to be included in nl-core profile?

### ISSUE THREAD

**Issue by LuudSlagter** [Nictiz/Nictiz-R4-zib2020#271]
In https://bits.nictiz.nl/browse/ZIB-1726 some textual changes in PharmaceuticalProduct are mentioned, that are used in the MP dataset. Should these be changed in the nl-core profile as well (this could be seen as a pre-adopt of the zib2022-1 release)?

**Comment by pieter-edelman-nictiz** [comment]
Related to #234 and #168 I guess, but with new insights into how errors in the zib are handled.

My thinking at the moment would be:
* Typos and other small and obvious fixes, if acknowledged by the zib centrum, are fixed in the zib layer.
* Things for which an erratum exists, are fixed in the zib layer (we should still determine how to document this).
* Things which are only present in a new (pre-)publication:
  * And which are incompatible with zib2020 cannot be implemented in the zib layer.
  * And which are additions to zib2020 and are otherwise compatible with zib2020 _could_ be implemented in the nl-core layer, but not in the zib layer (as it is not zib2020) (we still need to decide how to document this).
* The zib and nl-core profiles may _never_ be incompatible, even when it comes down to textual changes.
* If a textual change is clearly a _compatible_ improvement over the current text. then I would suggest adding it directly to the zib layer, not nl-core. (And if it's only a minor improvement, I wouldn't bother because then it maybe leads to confusion).

Any thoughts on this?

**Comment by pieter-edelman-nictiz** [comment]
Afterthought:
* If a zib turns out to be un-implementable, then perhaps it doesn't make sense to make a profile for it -- after all, an information standard is unable to use the zib anyway and needs to use the next (pre)publication.

**Comment by pieter-edelman-nictiz** [comment]
I think this issue has been sufficiently handled in #168 . Closing this ticket.
