### ISSUE TITLE
Naamgeving mapping-identity voor niet-zib mappings

### ISSUE THREAD

**Issue by pieter-edelman-nictiz** [Nictiz/Nictiz-R4-zib2020#286]
Nav. https://bits.nictiz.nl/browse/MM-3480:

> In de R4 profiling guidelines staat op dit moment niet aangegeven hoe de identity moet heten voor niet-zib mappings. Hoe moeten wij hiermee omgaan?
> 
> Voorstel is om deze als volgt op te bouwen:
> [Naam dataset] + [versie]
> Waarbij de naam van de dataset de voluit geschreven Engelse naam van de dataset is.
> 
> Voorbeeld voor Labuitwisseling zou zijn: Lab-Exchange-v3-0-0
> 
> In een vergelijkbare situatie hebben ze voor MedicatieProcess gekozen voor de volgende identity: Medication-Process-v9-2-0-0
> 
> Als hier een afspraak voor is gemaakt, dan moet dit uiteindelijk in de Profiling Guideline worden opgenomen.

**Comment by pieter-edelman-nictiz** [comment]
Volgens mij heeft een dataset geen naam, maar is "Lab Exchange" de naam van het project in ART-DECOR. De versie zou ik beperken tot major.minor

Dus dan zou het worden:
`[Engelse naam project]-v[versie]`
- Spaties worden vervangen door koppeltekens
- Versie wordt beperkt tot major.minor

**Comment by jduwel** [comment]
1 kleine opmerking: als het gaat om `.name` laten we (volgens je voorgestelde aanpassing op de wiki) in de zib variant een spatie staan, in de AD-dataset-variant wordt ook die spatie door een hyphen vervangen. Geen idee of dit nu 'inconsistent' is of niet. `.name` staat in beeld bij Simplifier, je zou kunnen zeggen dat het niet erg is daar een spatie te gebruiken.

**Comment by ahenket** [comment]
Any DECOR dataset has a stable id and a stable effectiveDate. You may version a dataset based on effectiveDate whilst keeping the id. The dataset name is not a stable property: it may be changed at any point in time. Using a dataset name in the mapping.identity, English if available or Dutch if not, may or may not turn out to be in sync with the original dataset. It would seem like a good idea to keep the version in the identity. The effectiveDate is a full timestamp, but you seldom need more than date. Ids also have a readable version as declared in the project ids. Normally that looks like "[prefix]dataset-[final part of id]", e.g. eafspraak-dataset-1.

Whatever you agree on in the mapping.identity shall be stable in that profile, regardless of newer ideas across profiles. It is a computable property that should not bear no real human relevance (but we all know it does in some cases).

Then there is the question of the url. We have ART-DECOR 2 and ART-DECOR 3 based urls. ART-DECOR development will at some point lead to deprecation of the v2 urls

* v2: [host]/art-decor/decor-datasets--[prefix]?id=[dataset id]&effectiveDate=[dataset effectiveDate]
* v3: [host]/ad/#/[prefix]/datasets/dataset/[dataset id]/[dataset effectiveDate]

In conclusion, my proposal is this for main declaration

* mapping.identity: lower-case([project prefix][dataset name][dataset effectiveDate as 'yyyymmdd'])
  * In some cases the project prefix is equal to the dataset name, e.g. eafspraak. Here the use of the id displayname is probably preferable. So not eafspraken-eafspraak-20170801, but eafspraken-dataset-1-20170801
  * Again I feel that stability inside the profile, and consistency across profiles for the same dataset is more important, than consistency across profiles for all datasets. If the latter means more to you then suggest to always use the human readable dataset id. 
* mapping.url: [v3 url to the dataset]
* mapping.name: ART-DECOR Dataset [dataset name] [dataset effectiveDate]
  * 'ART-DECOR' makes sense because the origin is then clearer
  * Some datasets have "dataset" in their name so 'Dataset ' should be considered optional if it duplicates

{code:xml}
<mapping>
  <identity value="eafspraak-dataset-1-20170801" />
  <uri value="https://decor.nictiz.nl/ad/#/eafspraken-/datasets/dataset/2.16.840.1.113883.2.4.3.11.60.61.1.1/2017-08-01T00:00:00" />
  <name value="ART-DECOR Dataset eAfspraak 2017-08-01T00:00:00" />
</mapping>
{code}

And on elements:

{code:xml}
<mapping>
  <identity value="eafspraak-dataset-1-20170801" />
  <map value="eafspraak-dataelement-36" />
  <comment value="ContactLocationType" />
</mapping>
{code}

**Comment by pieter-edelman-nictiz** [comment]
Gemerged naar prepub

**Comment by pieter-edelman-nictiz** [comment]
Dit ticket wordt afgesloten. Verdere discussie via https://bits.nictiz.nl/browse/MM-4685
