### ISSUE TITLE
How to profile zibs that can be mapped to a HL7 Vital Signs profile

### ISSUE THREAD

**Issue by ArdonToonstra** [Nictiz/Nictiz-R4-zib2020#62]
At least 7 zibs, listed in the [Vital Signs implementation guide](https://informatiestandaarden.nictiz.nl/wiki/MedMij:V2020.01/FHIR_VitalSigns), can be mapped to a [HL7 FHIR Vital Signs profile](http://hl7.org/fhir/R4/observation-vitalsigns.html). Due to technical problems and other mismatches encountered in STU3, it seems the better route to not derive profiles of the HL7 Vital Signs profiles but to create detached profiles that try to be compatible. 

This issue sets out to:

1. Describe and document the argumentation for not reusing an international standard. With the aim to document this in the relevant profiles.
2. Establish how we profile these 7 zibs so they are compatible and maintainable.

**Comment by pieter-edelman-nictiz** [comment]
Regarding 2: what kind of information would we need to "add" to the profiles in order to have Vital Signs compatibility?
* `Observation`: vs-2 constraint
* `Observation.category`: slice VSCat
* ~~`Observation.code`~~: this will be fixed to the zib supplied code(s)
* `Observation.effective[x]`: vs-1 constraint
* ~~`Observation.value[x]`~~: this only carries a comment about the Quantity datatype, but this seems superfluous because of the zib requirements.
* ~~`Observation.hasMember`~~: the Observation target is constrained to the VitalSigns profile, but in our use case there is no equivalent profile. A comment has been added that this can be used for vital sign panels, but this is the case anyway.
* ~~`Observation.derivedFrom`~~: the Observation target is constrained to the VitalSigns profile, but in our use case there is no equivalent profile.
* `Observation.component`:
  * ~~A remark has been added about systolic and diastolic blood pressure.~~ This seems more appropriate for the BloodPressure profile
  * vs-3 constraint
* ~~`Observation.component.code`~~: extensible bound to a restricted ValueSet of the codes that are used for the different Vital Sign components. This is unneeded as the codes will be defined in the downstream profiles.
* `Observation.value[x]`: bound to the Vital Signs Units Valuesets, which is basically UCUM. I'm not really sure how this works, but it seems like a good idea.
* ~~`Observation.component.dataAbsentReason`~~: only made _mustSupport_.

In addition, all these elements are made _mustSupport_. This is something we don't want to inherit.

There are two approaches to add these requirements to the seven profiles: to create a single base profile from where the zib profiles and subsequently the nl-core profiles are derived, or to add these elements separately (interpret these requirements as a kind of [interface description](https://build.fhir.org/uml.html#interface)). It seems most appropriate to introduce Vital Signs compatibility at the nl-core (use case) layer and keep the zib profiles "purely zib" (although this might not be 100% achievable, for example because of slice name requirements from Vital Signs), suggesting that the single base is not possible. Since the amount of information that needs to be added and the number of profiles are both limited, this doesn't seem to much of a problem.

**Comment by ArdonToonstra** [comment]
Nice work @pieter-edelman-nictiz, I agree that it introducing the Vital Signs compatibility at the nl-core layer seems doable. 

I believe you have now analysed the Vital Signs base profile. Every specific vital signs profile (e.g [HeartRate](http://hl7.org/fhir/heartrate.html) or [BodyHeight](http://hl7.org/fhir/bodyheight.html)) has some additional constraints. Mostly a specific fixed `.code` and a fixed or bound `.valueQuantity.code`. I assume we will use these as well. I imagine we can reuse the valuesets of HL? Like: http://hl7.org/fhir/valueset-ucum-bodylength.html

Since there are a lot of constraints on the valueQuantity, could we make a datatype profile for Quantity that already has the generic constraints?

**Comment by pieter-edelman-nictiz** [comment]
@ArdonToonstra good point. I agree with all these points.

**Comment by ArdonToonstra** [comment]
I believe we have a workable solution for 2. @jduwel can you work this out in the BloodPressure profile so it can lead as an example?

Next, we can work on some sentences for improved documentation on where the profiles deviate from vital signs ones and why.

**Comment by jduwel** [comment]
Tried to add all points to BloodPressure. Some notes:

- `Observation`: vs-2 constraint - Added to zib at the moment. Was some discussion wether to add to zib or nl-core layer. I guess if we agree to add it to our profiles we should try to add everything (or as much as possible) to the same level.
- `Observation.category`: slice VSCat - Added
- `Observation.effective[x]`: vs-1 constraint - Added. Goes a bit against zib datatype definition, but all zibs I checked define 'date and time' at the [...]DateTime concept so I guess it is safe to add.
- `Observation.component`: vs-3 constraint - Added to slices SystolicBP and DiastolicBP. I do wonder if it is feasible to add it to every `component`. Not all concepts that we map to `component` have a (conceptual) cardinality of 1..1, so maybe this is not something to add to a generic profile
- `Observation.value[x]`: bound to the Vital Signs Units Valuesets, which is basically UCUM. - Added. Specifically not added to `Observation.component.value[x]` because we sometimes use `component.valueCodeableConcept`.

When copying constraints, I noticed HL7 defines both `expression` and `xpath`. I copied both.

**Comment by pieter-edelman-nictiz** [comment]
Regarding vs-3: in the current version of the zib-BloodPressure branch, it is applied directly on `Observation.component`, not on the slices. However, I think it doesn't bite the conceptual cardinality concept; if a zib concept turns up missing in a use case, either the entire slice should be absent (in which case vs-3 doesn't apply for that concept), or there should be an explanation (in which case it aligns with vs-3); an empty slice wouldn't make much sense.

**Comment by pieter-edelman-nictiz** [comment]
My thought was to apply this at the use case level (nl-core), because the zib profiles can than (mostly) be "pure" zib. In fact, the reason not to use a common base profile is based on this assumption. @jduwel , why would you go for the zib layer?

**Comment by jduwel** [comment]
Yeah I guess nl-core is a better fit. I was under the impression that if you would need to add these points, you would already need to account for them in the zib layer. With what I have now added, that does not really seems to be the case.

This would be the case for some of the MAYs in the table on http://hl7.org/fhir/R4/observation-vitalsigns.html. What are your opinions on following these when some of them go against #58 for example?

**Comment by pieter-edelman-nictiz** [comment]
These extra codes aren't specified in the profiles, right? I think it's best to keep it that way.

**Comment by pieter-edelman-nictiz** [comment]
Something that we missed in our discussion so far is [the following remark](http://hl7.org/fhir/r4/observation.html#core):
> The following core <a href="http://hl7.org/fhir/r4/profiling.html">profiles</a> for the Observation resource have been defined as well. If implementations use this Resource when expressing the profile-specific concepts as structured data, they <strong>SHALL</strong> conform to the following profiles:</p>
> Profile | Description
> -- | --
> Vital signs | The FHIR Vital Signs profile sets minimum expectations for  the Observation Resource to record, search and fetch the vital signs  (e.g. temperature, blood pressure, respiration rate, etc.) associated  with a patient

So basically FHIR enforces us to be conformant with the Vital Signs profile for the corresponding zib profiles. As far as I can see, the analysis so far doesn't prevent this, _except_ for the constraint on related Observations -- if there are other Observations referenced in `.hasMember` or `.derivedFrom`, instances will not validate against the Vital Signs profile.

The only way to alleviate this is to derive all relevant zib profiles from Vital Signs, but this would mean the unwanted (because ill-defined) mustSupport will be included as well.

**Comment by pieter-edelman-nictiz** [comment]
One thing I overlooked; the VitalSigns profile has a _required_ binding on `Observation.component.value[x]` to the ValueSet http://hl7.org/fhir/ValueSet/ucum-vitals-common. This prevents many of the zib defined concepts to be modelled using a `.component`, as they oftentimes don't represent measurable things.

**Comment by pieter-edelman-nictiz** [comment]
To test out different scenario's, I've created the branch VitalSigns where all vital signs-like zibs are profiles, except for Respiration.

It turns out that it's not possible and probably not desirable to directly base these zib profiles on the HL7 VitalSigns profile or on the derived profiles:
* Impossible because `Observation.component.value[x]` has a required binding to http://hl7.org/fhir/ValueSet/ucum-vitals-common. This prevents to profile any concept that is not a measurement on `Observation.component`.
* Undesirable because it would mean inheriting `mustSupport` on a lot of elements, which is explicitly not wanted in the zib or nl-core layers.

The alternative then is to align as much as possible to HL7 Vital Signs profiles. This is not entirely possible for the following reasons:
* `Observation.hasMember` restricts the target Observations to the HL7 Vital Signs profile.
* `Observation.derivedFrom` restricts the target Observations to the HL7 Vital Signs profile.

Since this profile is nowhere to be used in the entire chain, it will not be possible to validate against this profile if one of these elements is used.

The parts that are cloned from the HL7 Vital Signs profile are:
* `Observation`: vs-2 constraint
* `Observation.category`: slice VSCat
* `Observation.effective[x]`: vs-1 constraint
* `Observation.component`: vs-3 constraint

The parts that are _not_ cloned from the HL7 Vital Signs profile are:
* `Observation.code` binding to the Vital Sings codes: this is not needed as there is no 'base' profile and the zib profiles will have fixed codes.
* `Observation.value[x]` comment; this is about the Quantity datatype, but this comment is superfluous
* `Observation.hasMember`: the Observation target is constrained to the VitalSigns profile, but in our use case there is no equivalent profile. A comment has been added that this can be used for vital sign panels, but this is the case anyway.
* `Observation.derivedFrom`: the Observation target is constrained to the VitalSigns profile, but in our use case there is no equivalent profile.
* `Observation.component`: A remark has been added about systolic and diastolic blood pressure. This seems more appropriate for the BloodPressure profile.
* `Observation.component.code`: _extensible_ bound to a restricted ValueSet of the codes that are used for the different Vital Sign components. This is unneeded as the codes will be defined in the downstream profiles.
* `Observation.value[x]`: bound to the Vital Signs Units Valuesets, which is basically UCUM. This prevents from using `Observation.component` for anything else.
* The `mustSupport` flags are ill-defined and unwanted at the zib/nl-core layer, and have not been cloned.

There are some minor friction points per zib:
* O2Saturation uses a different LOINC code that Vital Signs, but Vital Sings specifies it as an additional code. The zib is thus a refinement of the Vital Signs measurement.
* BodyTemperature uses a ValueSet with body temperature measurement methods (additionally bound on `Observation.code`), which Vital Signs specifies separate qualifier components for measurement site.
* BodyHeight specifies a separate qualifier component for position during measurement, while HL7 Vital Signs defines an additional `Observation.code.coding` for "body height measurement while lying down".
* HeadCircumference specifies that measurement units may be cm and mm, while HL7 Vital Signs restricts this to cm and inch.
* BloodPressure defines several components that can quite cleanly be mapped to core elements, but the HL7 Vital Signs IG describes them as "additional observations". However, I would argue that the HL7 IG is somewhat underspecified on this point and would suggest to go ahead with mapping these elements in the most logical way.

There is one additional case of interest: zib Respiration. This has no matching Vital Signs counterpart, but it contains a BreathingFrequency component, which aligns with Vital Signs Respiratory Rate. A case can be made to map this zib onto two related profiles, where the BreathingFrequency concept is communicated separately as a Vital Signs like Observation.

When creating the nl-core profiles, a pattern profile can be created (in the branch this profile is called pattern-VitalSigns) which carries the common elements. However, this should be applied to the zib layer. It is debatable whether this is desirable.

**Comment by ArdonToonstra** [comment]
First of all, I think we can continue with aligning as much as possible instead of basing on mainly because of the incorrect _required_ binding on `.component.value[x]`.

Two forgotten(?) constraints: the mandatory Patient reference on `.subject` and the mandatory and type constraints on `.effective[x]`. These have been added to the vitalSignsPattern profile. Also added the `condition` elements... its debatable if you want them there too. 
 
I think we want to work with some kind of pattern profile that contains all the HL7 Vital Signs constraints. This keeps it nicely separated from all the stuff we will add and works best in the later governance of the profiles. I am not sure if it is best to use such a pattern profile before the zib layer...
How about: zib-[vital sign] > pattern-VitalSigns-[vital sign] > nl-core-[vital sign]
This would duplicate the pattern-VitalSigns profiles quite, but it makes the zib layer perhaps more zib/logical model/consistent etc.

This would dbu

**Comment by pieter-edelman-nictiz** [comment]
> Two forgotten(?) constraints: the mandatory Patient reference on .subject and the mandatory and type constraints on .effective[x]. These have been added to the vitalSignsPattern profile.

I left Patient out because that's something for the nl-core layer (the zib profiles are marked "abstract" so here's an opportunity to align a bit to our own guidelines). But you're right, these should at least be applied to the nl-core layer. This breaks our Open World Modelling approach a bit, but aligns better to FHIR.

> How about: zib-[vital sign] > pattern-VitalSigns-[vital sign] > nl-core-[vital sign]
This would duplicate the pattern-VitalSigns profiles quite, but it makes the zib layer perhaps more zib/logical model/consistent etc.

This doesn't make much sense to me. There's no pattern that you can "apply" to an existing profile (you're thinking of an interface), you'd have to manually copy over everything, in which case you can copy it directly to the nl-core layer.

> With regards to the other friction points: do we need to make agreements on whether to use the .components or (additional) .code values? I am gently in favour of consistently use .components.

This depends on the ValueSets. zib BodyTemperature specifies a ValueSet that includes codes for "body temperature as measured using [xxx]". This *is* an additional Observation code. BodyHeight OTOH specifies a ValueSet that includes qualifiers without context (so not "body height while lying", but just "lying position"). This is something that should be postcoordinted with the main code (which is not possible here), go into `.method` (which wouldn't be semantically correct in this particular case) or go into a `.component`. I think it would be way too complex to "map" the zib concepts onto the HL7 Vital Signs concepts.

**Comment by pieter-edelman-nictiz** [comment]
One more question: do we create Observation.code.coding slices in the same way as VitalSigns or in "our" way? The result for the instances would be the same.

**Comment by pieter-edelman-nictiz** [comment]
The current approach is to use a single pattern profile to base the zib profiles off. This ensures consistency accros all profiles. This pattern can also add the documentation on why the HL7 Vital Signs profile isn't used in a consistent way. Where possible, our current profiling guidelines are followed to be as consistent as possible with the other zib profiles.

One question remains: the zib BloodPressured defines a few SNOMED codes that are also defined by HL7 Vital Signs as LOINC codes. Which one should we use? Or should we use both?

**Comment by pieter-edelman-nictiz** [comment]
Proposal for documenting the approach: https://informatiestandaarden.nictiz.nl/wiki/FHIR:Vissue-Github-62_FHIR_Profiling_Guidelines_R4#HL7_Vital_Signs
