### ISSUE TITLE
Mapping initials and full given names in zib NameInformation

### ISSUE THREAD

**Issue by pieter-edelman-nictiz** [Nictiz/Nictiz-R4-zib2020#82]
The [zib 2020 NameInformation](https://zibs.nl/wiki/NameInformation-v1.1(2020EN)) is on quite fundamental level incompatible with FHIR R4 datatype [HumanName](https://hl7.org/fhir/datatypes.html#HumanName). The zib specifies that (a list of) given names (NL-CM:20.4.4) and (a list of) initials (NL-CM:20.4.5) may both be communicated separately. However, in FHIR there is no way to communicate BOTH initials and full given names within the same HumanName instance -- for each given name, you communicate EITHER an initial or a full name.

This could be alleviated by specifying that initials are communicated when only an initial is known, and the full name otherwise. However, the zib specifies full names and initials as discrete lists without any relation between the full names and initials at all. For example, it may be that only a single full name is known and three initials, and it may be that the full name represents the second initial, or none of the initials at all. So there's no way to mix and match full names and initials.

The only proper way to model this, is by repeating the _entire_ HumanName instance, once with the initials and once with the full names. Both instances could get a `.use` of _official_.

Another approach would be to allow mixing and matching full names and initials. The zib concepts would then have to be derived from that information, for example
* "Abraham B." would result in "A. B." for initials and "Abraham" for given names.
* "A. B" would result in "A. B." for initials and given names absent.
* "Abraham Bob" would result in "A. B" for initials and "Abraham Bob" for given names.

**Comment by pieter-edelman-nictiz** [comment]
Related: https://bits.nictiz.nl/browse/ZIB-1435

**Comment by pieter-edelman-nictiz** [comment]
Asked Zulip for help: https://chat.fhir.org/#narrow/stream/179166-implementers/topic/Communicating.20both.20full.20names.20and.20initials

**Comment by ArdonToonstra** [comment]
Perhaps too simplistic, but perhaps we should just go for specifying that initials are communicated when only an initial is known, and the full name otherwise AND documenting that in some rare cases you want to send both this should go in two separate HumanName instances?

**Comment by pieter-edelman-nictiz** [comment]
I'm in favor of this, but it's a bit more elaborate; you'd have to break up the "given names" string and "initial string" from the zib into their constituent parts and then communicate them independently, where you apply the above rule. And then you can use the escape of two instances for the weird case where you have a list of given names and a list of initials and you really don't know how they relate to each other.

**Comment by pieter-edelman-nictiz** [comment]
Example of how this might look like: https://simplifier.net/test20201185/~resources?category=Profile&sortBy=DisplayName_desc

Examples in these profiles are not up-to-date.

**Comment by weteringac** [comment]
Okay, interesting. I guess HL7v3 (maybe not surprising) obeys the same mechanism as FHIR. However, the zib-definition does not. 

Zib seems to implicate when sending initials and/or full given names one should always be complete (or that may be a valid assumption: if not that is the problem of the sourcesystem not a problem of zib/information standard).

When transforming from V3 to FHIR or vice versa, we could add an ada field that conveys the HL7-definition for given name, thus minimizing information loss AND minimizing this problem in real life. 

Should we encounter an ada/zib instance which does have both initials and full name, we can then send two instances of human name, but I suspect that should hardly ever happen. Source systems which natively support either FHIR or HL7v3 are asked to comply to those rules (more so than zib rules, which only conceptually define initiales and full names, but do not have technical specifications). 
We can instruct our own information analysts to choose between full name and initials in most of the test instances (except one, because we do want to validate target systems on this edge use case).

Profile mapping may be a bit complex but not undoable.

**Comment by pieter-edelman-nictiz** [comment]
The (hopefully temporary) solution to this issue is documented in https://nictiz.atlassian.net/browse/ZIBFHIR-20. Closing this ticket.
